BEGIN;

--

-- Create model Category

--

CREATE TABLE
    "category" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name" varchar(100) NOT NULL UNIQUE
    );

--

-- Create model Expense

--

CREATE TABLE
    "expense" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "timestamp" timestamp
        with
            time zone NOT NULL,
            "amount" double precision NOT NULL,
            "description" varchar(255) NULL,
            "category_id" bigint NOT NULL
    );

CREATE INDEX
    "category_name_a15ca2a4_like" ON "category" ("name" varchar_pattern_ops);

ALTER TABLE "expense"
ADD
    CONSTRAINT "expense_category_id_05ebe6bf_fk_category_id" FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX
    "expense_category_id_05ebe6bf" ON "expense" ("category_id");

--

-- Insert data in Category Table

--

COMMIT;
